language: java
sudo: false

jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - git submodule update --init --recursive

install: ""

after_success:
  - mvn clean
  - mvn cobertura:cobertura coveralls:report
